{{- if and (not .Values.ingestToken.existingSecret) .Values.ingestToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icp-agent.secretName" . }}
  labels:
    {{- include "icp-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ingestToken.secretKey }}: {{ .Values.ingestToken.value | quote }}
{{- end }}
